### ISSUE TITLE
Is possible to define separator, in French thousand separator as made by space and not comma ? 

### ISSUE THREAD

**Issue by zairino** [ecomfe/echarts#4180]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
Yes you can format the label by yourself using the `formatter` option

**Comment by zairino** [comment]
Not the label the thousand separator i hack this part of your js file :


function addCommas(x) {     if (isNaN(x)) {         return '-';     }     x = (x + '').split('.');     return x[0].replace(/(\d{1,3})(?=(?:\d{3})+(?!\d))/g, '$1 ') + (x.length > 1 ? '.' + x[1] : ''); }

so if you can add in some options the ability to define the thousandSeparator ;)

**Comment by astik** [comment]
Hi all,
I run into the same issue with the current latest version.

It is too bad that the default formatter use an hardcoded function like addCommas to format numbers. Of course, we can redefine the formatter for each use case (xAxis.axisLabel, xAxis.axisPointer.label, yAxis.axisLabel, yAxis.axisPointer.label, ...) but this is a lot of work for a default behavior. At least, it should use browser locale to define which ways to format number.

Here is an example :

```
option = {
    tooltip: {
        trigger: 'axis',
			axisPointer: {
				type: 'cross'
			}
    },
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value',
        axisLabel: {
            formatter: '{value}'
        },
        axisPointer: {
            label:{
                formatter: function(a){return a.value.toFixed(2)}
            }
        }
    },
    series: [
        {
            name:'A',
            type:'line',
            data:[120000.5, 132000.5, 101000.5, 134000.5, 90000.5, 230000.5, 210000.5]
        },
        {
            name:'B',
            type:'line',
            data:[220000.5, 282000.5, 201000.5, 234000.5, 290000.5, 430000.5, 410000.5]
        }
    ]
};
```

As you can see, i redefined formater for yAxis.axisLabel and yAxis.axisPointer.label. Still, i need to do it also for tooltip content. As i'm working with multi-series, the tooltip is different than the other and is much more complicated.

Redefining the formatter should be a workaraound but it shouldn't be enough to close this issue =/

**Comment by astik** [comment]
One thing to consider as an easy fix : toLocaleString
* cn : https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
* en : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

It would display number the right way by default depending on environment locale.

**Comment by JohnCoene** [comment]
Hi Artem,

Thanks again for this, really useful!

I've implemented the axis formatter, [here](https://github.com/JohnCoene/echarts4r/commit/8896675bff862b343af22e32dd39512116ee00c4)

`e_axis` takes a new argument `formatter` to which one passes the formatter. I've made the `locale` optional and is inferred from `Sys.getlocale()` and changed the default currency to USD. 

```r
library(echarts4r)

cars %>% 
  e_charts(speed) %>% 
  e_scatter(dist) %>% 
  e_y_axis(
    formatter = e_axis_formatter("currency")
  ) 
``` 

I've done something similar for the tooltips [here](https://github.com/JohnCoene/echarts4r/commit/f61e3726a9cf9cd9f46e842331dea92976944f91), however I cannot get them to work for some reason. There are errors in the JS or I use them wrongly.

```r
# does not work
cars %>% 
  dplyr::mutate(
    dist = dist / 25
  ) %>% 
  e_charts(speed) %>% 
  e_scatter(dist) %>% 
  e_tooltip(
    item_formatter = e_tooltip_item_formatter("percent")
  )
```

Let me know what you think.

**Comment by maljac** [comment]
@pissang I think the issue is still there:
https://github.com/apache/incubator-echarts/blob/7887f27a0ff47611d84109f9c9b202b8eaa31094/src/util/format.js#L30

As @astik mentions, it is a lot of work to redefine all formatters for the proper display of the correct thousand / decimal separator.

**Comment by pynomaly** [comment]
I'm also interested in a simpler way to display the correct number format. @pissang Is there any advance in this issue?

**Comment by develar** [comment]
There is no possibility to provide own implementation of [makeValueReadable](https://github.com/apache/echarts/blob/a302c0c80adc478d45043f4014029d74263acd36/src/util/format.ts#L80). There is the only way — to set `formatter`, but in this case you loose default excellent presentation and have to duplicate it somehow.

**Comment by Vovan-VE** [comment]
[`Intl.NumberFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat)?

**Comment by Vovan-VE** [comment]
There are lots of variations for thousand and decimal separators across different languages. For example, seeing `12345.0` as "**12,345**" instead of "**12 345**" is very confusing for cyrillic languages since "**12,345**" means `12.345` .

**Comment by develar** [comment]
@Vovan-VE Yes, in my app I use Intl.NumberFormat / Intl.DateTimeFormat. Issue is that 1) you cannot easily set it globally 2) for `tooltip. formatter ` you have to duplicate a lot of complex logic, because you want standard tooltip with just changed number/time formatting. 

Probably, it is easy to send PR, maybe I will do it when I will finish my app.

**Comment by irbian** [comment]
We are experimenting this too. We can see it has been mentioned in other issues like #14516 , #17419 and #18264

> @Vovan-VE Yes, in my app I use Intl.NumberFormat / Intl.DateTimeFormat. Issue is that 1) you cannot easily set it globally (#8294) 2) for `tooltip. formatter ` you have to duplicate a lot of complex logic, because you want standard tooltip with just changed number/time formatting.
> 
> Probably, it is easy to send PR, maybe I will do it when I will finish my app.

Did you were able to make the PR?
